name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Generates the snake animation
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: SakshamJain9999
          outputs: dist/snake.svg

      # Push the snake to the output branch
      - name: Push snake to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
